import type { Metadata } from "next";
import { Gauge, GraduationCap, ShieldCheck, Users } from "lucide-react";
import { BriefForm } from "@/components/forms/brief-form";
import { PageHero } from "@/components/ui/page-hero";

export const metadata: Metadata = { title: "Careers", description: "Explore manufacturing, engineering, quality, supply-chain, and project-support career paths with Corvex Steel Wires.", alternates: { canonical: "/careers" } };

export default function CareersPage() {
  const values = [{ icon: ShieldCheck, title: "Safety before speed", copy: "Good work begins with controlled conditions and the confidence to raise concerns." }, { icon: Gauge, title: "Precision with purpose", copy: "Details matter because customers build operational systems around what we deliver." }, { icon: GraduationCap, title: "Learn at the line", copy: "We value practical curiosity, disciplined improvement, and knowledge shared across functions." }, { icon: Users, title: "Own the handoff", copy: "Engineering, quality, production, planning, and service succeed through clear interfaces." }];
  return <><PageHero eyebrow="Careers" title="Build what protects." accent="Grow while doing it." copy="Join a team where manufacturing discipline, technical curiosity, and accountable collaboration shape every project." /><section className="bg-paper-50 py-20 md:py-28"><div className="container-shell"><div className="max-w-3xl"><p className="eyebrow text-signal-600">How we work</p><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] md:text-6xl">Standards you can build a career around.</h2></div><div className="mt-12 grid gap-px overflow-hidden rounded-2xl border border-ink-950/10 bg-ink-950/10 md:grid-cols-2 lg:grid-cols-4">{values.map((item) => <article key={item.title} className="bg-white p-7"><item.icon aria-hidden="true" className="text-signal-600" size={26} /><h3 className="mt-6 text-xl font-semibold">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate-700">{item.copy}</p></article>)}</div></div></section><section className="bg-mist-100 py-20 md:py-28"><div className="container-shell grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-20"><div><p className="eyebrow text-signal-600">Open applications</p><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] md:text-5xl">Show us where you can contribute.</h2><p className="mt-6 leading-7 text-slate-700">Current vacancies vary with operational needs. Registering interest does not guarantee an interview or employment offer; relevant profiles may be considered when an authorised role becomes available.</p><div className="mt-7 rounded-xl border border-ink-950/10 bg-white p-5 text-sm leading-6 text-slate-700"><strong className="text-ink-950">Recruitment safety:</strong> Corvex does not ask candidates to pay an application, interview, equipment, or onboarding fee.</div></div><BriefForm mode="career" /></div></section></>;
}
