import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import {
  ArrowDown, ArrowRight, Boxes, CheckCircle2, Factory, Gauge, HardHat, Leaf,
  Network, PackageCheck, ScanLine, Settings2, ShieldCheck, Warehouse, Wrench,
} from "lucide-react";

import { CapabilityMap } from "@/sections/infrastructure/capability-map";
import { Reveal } from "@/sections/home/home-interactions";

export const metadata: Metadata = {
  title: "Infrastructure",
  description: "Explore the infrastructure logic behind Corvex material control, production cells, tooling, inspection, packaging, warehousing, safety, and scalable project delivery.",
  alternates: { canonical: "/infrastructure" },
  openGraph: { title: "Corvex Manufacturing Infrastructure", description: "A connected production environment designed around visible flow and controlled handoffs.", url: "/infrastructure" },
};

export default function InfrastructurePage() {
  return (
    <>
      <section className="relative isolate min-h-[calc(100svh-5rem)] overflow-hidden bg-ink-950 text-white">
        <Image src="/images/home/manufacturing-floor.png" alt="Modern Corvex steel wire production environment and controlled manufacturing cell" fill priority sizes="100vw" className="object-cover" />
        <div className="absolute inset-0 bg-[linear-gradient(90deg,#08111c_0%,rgba(8,17,28,.9)_38%,rgba(8,17,28,.2)_80%),linear-gradient(to_top,#08111c_0%,transparent_48%)]" />
        <div className="industrial-grid absolute inset-0 opacity-25" aria-hidden="true" />
        <div className="container-shell relative flex min-h-[calc(100svh-5rem)] flex-col justify-between pb-10 pt-20 md:pt-28"><Reveal><p className="eyebrow text-signal-500">Infrastructure</p><h1 className="mt-7 max-w-6xl text-[clamp(3.5rem,8vw,8rem)] font-semibold leading-[.91] tracking-[-.065em] text-balance">Capability,<br/><span className="text-steel-300">connected by design.</span></h1></Reveal><Reveal delay={.08} className="grid gap-8 border-t border-white/15 pt-8 md:grid-cols-[1fr_auto] md:items-end"><p className="max-w-2xl text-lg leading-8 text-steel-300">Infrastructure is more than machines. It is the flow, tooling, inspection, utilities, people, safety, storage, and information that allow production to stay controlled.</p><a className="inline-flex items-center gap-3 font-mono text-xs uppercase tracking-[.14em] text-steel-300" href="#capability-map"><ArrowDown aria-hidden="true" className="text-signal-500" size={18}/> Explore the system</a></Reveal></div>
      </section>

      <section className="bg-paper-50 py-20 md:py-32"><div className="container-shell grid gap-12 lg:grid-cols-[.65fr_1.35fr] lg:gap-24"><Reveal><p className="eyebrow text-signal-600">Our infrastructure position</p><Network aria-hidden="true" className="mt-8 text-signal-600" size={38}/></Reveal><Reveal delay={.08}><h2 className="text-4xl font-semibold leading-[1.08] tracking-[-.05em] md:text-6xl">The value is not in isolated equipment. It is in connected control.</h2><p className="mt-8 max-w-4xl text-xl leading-9 text-slate-700">A capable production environment makes status, movement, handoffs, maintenance, quality, and project identity easier to understand. That connection is what turns equipment into dependable infrastructure.</p></Reveal></div></section>

      <section id="capability-map" className="scroll-mt-24 bg-ink-950 py-20 text-white md:py-28"><div className="container-shell"><Reveal className="grid gap-8 md:grid-cols-[1fr_.65fr] md:items-end"><div><p className="eyebrow text-signal-500">Capability map</p><h2 className="mt-6 max-w-5xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Follow the product through the facility.</h2></div><p className="max-w-lg leading-7 text-steel-300">Explore how seven infrastructure zones support controlled flow from incoming material to dispatch.</p></Reveal><div className="mt-14"><CapabilityMap/></div></div></section>

      <section className="bg-mist-100 py-20 md:py-28"><div className="container-shell"><Reveal><p className="eyebrow text-signal-600">Production environment</p><h2 className="mt-6 max-w-5xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Infrastructure that supports the process—not interrupts it.</h2></Reveal><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[[Factory,"Process-led layout","Arrange work around production families, movement, checks, and safe access."],[Settings2,"Setup readiness","Support tooling, changeover, first-piece review, and controlled adjustment."],[ScanLine,"Quality proximity","Position inspection resources close enough to influence the production decision."],[Warehouse,"Visible status","Separate incoming, in-process, hold, released, and dispatch-ready material."]].map(([Icon,title,copy],index)=>{const CapabilityIcon=Icon as typeof Factory;return <Reveal key={title as string} delay={index*.05} className="group rounded-2xl border border-ink-950/10 bg-white p-7 transition-all hover:-translate-y-1 hover:border-signal-500/40 hover:shadow-[0_18px_50px_rgba(8,17,28,.08)]"><span className="font-mono text-xs text-signal-600">0{index+1}</span><CapabilityIcon aria-hidden="true" className="mt-10 text-signal-600" size={29}/><h3 className="mt-8 text-xl font-semibold">{title as string}</h3><p className="mt-4 text-sm leading-6 text-slate-700">{copy as string}</p></Reveal>})}</div></div></section>

      <section className="bg-paper-50 py-20 md:py-32"><div className="container-shell grid gap-12 lg:grid-cols-2 lg:gap-16"><Reveal className="relative min-h-[34rem] overflow-hidden rounded-3xl"><Image src="/images/home/manufacturing-floor.png" alt="Steel mesh production line arranged for safe inspection and material flow" fill sizes="(min-width:1024px) 50vw,100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-ink-950/70 via-transparent to-transparent"/><div className="absolute bottom-7 left-7 right-7 text-white"><p className="eyebrow text-signal-500">Flow before scale</p><p className="mt-4 max-w-md text-2xl font-semibold">A clear route for material, people, status, and information.</p></div></Reveal><Reveal delay={.08} className="flex flex-col justify-center"><p className="eyebrow text-signal-600">Scalable by logic</p><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] md:text-5xl">Growth should extend control, not dilute it.</h2><p className="mt-7 text-lg leading-8 text-slate-700">Scalable infrastructure begins with modular process thinking: defined cells, repeatable interfaces, flexible staging, maintainable utilities, and inspection capacity that grows with production demand.</p><ul className="mt-9 space-y-4 border-t border-ink-950/15 pt-7">{["Modular production and support zones","Utilities planned around safe access and maintenance","Storage aligned with status and project sequence","Quality resources considered alongside output demand"].map((item)=><li key={item} className="flex items-center gap-3 text-sm font-semibold"><CheckCircle2 aria-hidden="true" className="text-signal-600" size={18}/>{item}</li>)}</ul></Reveal></div></section>

      <section className="bg-navy-900 py-20 text-white md:py-28"><div className="container-shell grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-24"><Reveal><p className="eyebrow text-signal-500">The infrastructure beneath output</p><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] md:text-5xl">Systems that keep systems running.</h2></Reveal><Reveal delay={.08} className="grid gap-px overflow-hidden rounded-2xl bg-white/10 sm:grid-cols-2">{[[Wrench,"Maintenance","Planned care, accessible equipment, spares logic, and visible service status."],[Gauge,"Calibration context","Measurement resources maintained and selected for the characteristic being checked."],[HardHat,"Safety","Movement, guarding, handling, access, and task controls designed into the environment."],[ShieldCheck,"Utilities","Power, lighting, ventilation, lifting, and support services aligned with process needs."],[Boxes,"Material handling","Suitable movement and storage methods that protect product condition and people."],[PackageCheck,"Dispatch readiness","Packaging, loading, identity, documentation, and shipment sequence connected."]].map(([Icon,title,copy],index)=>{const SupportIcon=Icon as typeof Wrench;return <div key={title as string} className="bg-ink-950 p-7"><div className="flex items-start justify-between"><span className="font-mono text-xs text-signal-500">0{index+1}</span><SupportIcon aria-hidden="true" className="text-steel-300" size={23}/></div><h3 className="mt-8 text-xl font-semibold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-steel-300">{copy as string}</p></div>})}</Reveal></div></section>

      <section className="bg-mist-100 py-20 md:py-28"><div className="container-shell grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:gap-24"><Reveal><p className="eyebrow text-signal-600">People and environment</p><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] md:text-5xl">A capable facility must support the people inside it.</h2><p className="mt-6 max-w-sm leading-7 text-slate-700">Infrastructure decisions influence safety, clarity, physical effort, skill development, resource use, and the ability to improve.</p></Reveal><Reveal delay={.08} className="grid gap-4 sm:grid-cols-2">{[[HardHat,"Safer work","Clear movement, task access, guarding, lifting, and housekeeping expectations."],[Gauge,"Skilled decisions","Workstations and information that help people understand setup, status, and checks."],[Leaf,"Resource awareness","Material yield, energy, consumables, waste separation, and durable equipment choices."],[Network,"Continuous improvement","Layouts and information paths that make recurring issues easier to see and address."]].map(([Icon,title,copy])=>{const ValueIcon=Icon as typeof HardHat;return <div key={title as string} className="rounded-2xl border border-ink-950/10 bg-white p-7"><ValueIcon aria-hidden="true" className="text-signal-600" size={26}/><h3 className="mt-8 text-xl font-semibold">{title as string}</h3><p className="mt-4 text-sm leading-6 text-slate-700">{copy as string}</p></div>})}</Reveal></div></section>

      <section className="bg-paper-50 py-20 md:py-28"><div className="container-shell"><Reveal className="grid gap-8 md:grid-cols-[1fr_.65fr] md:items-end"><div><p className="eyebrow text-signal-600">Evidence before claims</p><h2 className="mt-6 max-w-4xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Capability should be demonstrated against the project.</h2></div><p className="max-w-lg leading-7 text-slate-700">Machine lists and capacity figures become meaningful only when connected to the required product, tolerance, quantity, release plan, and evidence.</p></Reveal><div className="mt-14 grid gap-4 md:grid-cols-3">{[["01","Product fit","Can the equipment, tooling, material path, and checks support the required configuration?"],["02","Volume fit","Can planning, production, inspection, storage, and dispatch support the agreed release sequence?"],["03","Evidence fit","Can the required submittals, inspection records, identification, and release documents be produced?"]].map(([number,title,copy])=><div key={number} className="rounded-2xl border border-ink-950/10 p-7"><span className="font-mono text-xs text-signal-600">{number}</span><h3 className="mt-10 text-xl font-semibold">{title}</h3><p className="mt-4 text-sm leading-6 text-slate-700">{copy}</p></div>)}</div><p className="mt-7 text-xs leading-5 text-slate-500">Verified facility dimensions, machine inventory, installed capacity, output rates, and utility data should be added only from approved Corvex records.</p></div></section>

      <section className="relative overflow-hidden bg-signal-600 py-24 text-white md:py-32"><div className="container-shell relative grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><Reveal><p className="eyebrow text-white/70">Match capability to the requirement</p><h2 className="mt-6 max-w-5xl text-5xl font-semibold leading-[1.02] tracking-[-.055em] text-balance md:text-7xl">Bring the product, volume, and release plan.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/80">A technical review can connect the desired configuration to tooling, process flow, inspection, packaging, and project timing.</p></Reveal><Reveal delay={.1}><Link className="button border-white bg-white text-ink-950 hover:bg-paper-50" href="/request-a-quote">Review project capability <ArrowRight aria-hidden="true" size={18}/></Link></Reveal></div></section>
    </>
  );
}
