import type { Metadata } from "next";
import { Clock3, FileCheck2, Mail, MapPin, MessagesSquare, Phone } from "lucide-react";
import { BriefForm } from "@/components/forms/brief-form";
import { PageHero } from "@/components/ui/page-hero";
import { SocialMark } from "@/components/ui/social-mark";
import { contactDetails } from "@/constants/contact";

export const metadata: Metadata = { title: "Contact", description: "Contact Corvex Steel Wires for perimeter products, project coordination, quality documentation, order support, and technical enquiries.", alternates: { canonical: "/contact" }, openGraph: { title: "Contact Corvex Steel Wires", description: "Start a clear conversation about your perimeter project.", url: "/contact" } };

export default function ContactPage() {
  const cards = [
    { icon: MessagesSquare, title: "Project enquiries", copy: "Products, quantities, site context, programmes, and commercial coordination." },
    { icon: FileCheck2, title: "Technical records", copy: "Product data, inspection requirements, traceability, and document planning." },
    { icon: Clock3, title: "Business hours", copy: `${contactDetails.hours}. Project responses are prioritised by urgency and information quality.` },
  ];
  return <><PageHero eyebrow="Contact" title="Start with context." accent="Leave with clarity." copy="Tell us what the site needs, where the project stands, and which decisions remain open." /><section className="bg-paper-50 py-20 md:py-28"><div className="container-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><div><p className="eyebrow text-signal-600">Route your request</p><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] md:text-5xl">Useful answers begin with useful inputs.</h2><div className="mt-9 divide-y divide-ink-950/15">{cards.map((card) => <div key={card.title} className="flex gap-5 py-6"><card.icon aria-hidden="true" className="shrink-0 text-signal-600" size={24} /><div><h3 className="font-semibold">{card.title}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{card.copy}</p></div></div>)}</div><div className="mt-8 rounded-2xl bg-mist-100 p-6"><span className="inline-flex rounded-full bg-signal-200 px-3 py-1 font-mono text-[.65rem] font-semibold uppercase tracking-[.12em] text-ink-950">Temporary details</span><div className="mt-5 space-y-4"><a className="flex items-start gap-3 text-sm font-semibold hover:text-signal-600" href={contactDetails.phone.href}><Phone aria-hidden="true" className="mt-0.5 shrink-0 text-signal-600" size={19}/>{contactDetails.phone.label}</a><a className="flex items-start gap-3 text-sm font-semibold hover:text-signal-600" href={contactDetails.email.href}><Mail aria-hidden="true" className="mt-0.5 shrink-0 text-signal-600" size={19}/>{contactDetails.email.label}</a><p className="flex items-start gap-3 text-sm leading-6 text-slate-700"><MapPin aria-hidden="true" className="mt-0.5 shrink-0 text-signal-600" size={19}/>{contactDetails.address}</p></div><div className="mt-6 flex flex-wrap gap-2">{contactDetails.socials.map((social) => <a key={social.label} href={social.href} target="_blank" rel="noreferrer" aria-label={`${social.label}: ${social.handle}`} className="flex h-11 w-11 items-center justify-center rounded-full border border-ink-950/10 bg-white text-slate-700 transition hover:-translate-y-0.5 hover:border-signal-500 hover:text-signal-600"><SocialMark platform={social.label}/></a>)}</div><p className="mt-5 text-xs leading-5 text-slate-500">Replace these temporary values in <code>src/constants/contact.ts</code> before launch.</p></div></div><BriefForm mode="contact" /></div></section></>;
}
