import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import {
  ArrowDown, ArrowRight, BarChart3, Boxes, CheckCircle2, Droplets, Factory,
  Gauge, Leaf, Recycle, ShieldCheck, Sparkles, Target, Truck,
} from "lucide-react";

import { LifecycleExplorer } from "@/sections/sustainability/lifecycle-explorer";
import { Reveal } from "@/sections/home/home-interactions";

export const metadata: Metadata = {
  title: "Sustainability",
  description: "Explore the Corvex lifecycle approach to material efficiency, responsible production, durability, packaging, logistics, maintenance, recovery, and measurable environmental evidence.",
  alternates: { canonical: "/sustainability" },
  openGraph: { title: "Corvex Sustainability", description: "Lifecycle thinking for stronger, more resource-aware steel wire and perimeter systems.", url: "/sustainability" },
};

export default function SustainabilityPage() {
  return (
    <>
      <section className="relative isolate min-h-[calc(100svh-5rem)] overflow-hidden bg-ink-950 text-white"><Image src="/images/industries/energy-utilities.png" alt="Renewable energy and utility infrastructure across a dry landscape" fill priority sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,#08111c_0%,rgba(8,17,28,.91)_42%,rgba(8,17,28,.22)_82%),linear-gradient(to_top,#08111c_0%,transparent_48%)]"/><div className="industrial-grid absolute inset-0 opacity-20" aria-hidden="true"/><div className="container-shell relative flex min-h-[calc(100svh-5rem)] flex-col justify-between pb-10 pt-20 md:pt-28"><Reveal><p className="eyebrow text-signal-500">Sustainability</p><h1 className="mt-7 max-w-6xl text-[clamp(3.5rem,8vw,8rem)] font-semibold leading-[.91] tracking-[-.065em] text-balance">Strength across<br/><span className="text-steel-300">the lifecycle.</span></h1></Reveal><Reveal delay={.08} className="grid gap-8 border-t border-white/15 pt-8 md:grid-cols-[1fr_auto] md:items-end"><p className="max-w-2xl text-lg leading-8 text-steel-300">Responsible steel systems begin with clear boundaries, measurable decisions, durable design, efficient production, and realistic recovery pathways.</p><a className="inline-flex items-center gap-3 font-mono text-xs uppercase tracking-[.14em] text-steel-300" href="#lifecycle"><ArrowDown aria-hidden="true" className="text-signal-500" size={18}/> Explore the lifecycle</a></Reveal></div></section>

      <section className="bg-paper-50 py-20 md:py-32"><div className="container-shell grid gap-12 lg:grid-cols-[.65fr_1.35fr] lg:gap-24"><Reveal><p className="eyebrow text-signal-600">Our sustainability position</p><Leaf aria-hidden="true" className="mt-8 text-signal-600" size={39}/></Reveal><Reveal delay={.08}><h2 className="text-4xl font-semibold leading-[1.08] tracking-[-.05em] md:text-6xl">A claim becomes credible when its boundary, method, and evidence are visible.</h2><p className="mt-8 max-w-4xl text-xl leading-9 text-slate-700">We approach sustainability as a sequence of technical and operating decisions—not a decorative label. Material, yield, durability, energy, packaging, logistics, maintenance, and end-of-life each need their own context and measure.</p></Reveal></div></section>

      <section id="lifecycle" className="scroll-mt-24 bg-mist-100 py-20 md:py-28"><div className="container-shell"><Reveal className="grid gap-8 md:grid-cols-[1fr_.65fr] md:items-end"><div><p className="eyebrow text-signal-600">Interactive lifecycle</p><h2 className="mt-6 max-w-5xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Make responsibility part of every stage.</h2></div><p className="max-w-lg leading-7 text-slate-700">Explore six lifecycle stages, practical decision levers, and the evidence needed to support them.</p></Reveal><div className="mt-14"><LifecycleExplorer/></div></div></section>

      <section className="bg-ink-950 py-20 text-white md:py-28"><div className="container-shell"><Reveal><p className="eyebrow text-signal-500">Four responsibility pillars</p><h2 className="mt-6 max-w-5xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Focus effort where operations can act.</h2></Reveal><div className="mt-14 grid gap-px overflow-hidden rounded-2xl bg-white/10 md:grid-cols-2 lg:grid-cols-4">{[[Gauge,"Material efficiency","Improve yield, coordinate geometry, reduce avoidable variation, and separate recoverable steel."],[Factory,"Responsible operations","Understand energy, consumables, maintenance, water, waste, and safe working conditions."],[ShieldCheck,"Durable systems","Select material and finish for exposure, support inspection, and enable practical repair."],[Recycle,"Circular readiness","Preserve material identity, support separation, reuse suitable components, and enable recovery."]].map(([Icon,title,copy],index)=>{const PillarIcon=Icon as typeof Gauge;return <Reveal key={title as string} delay={index*.05} className="group bg-ink-950 p-8 transition-colors hover:bg-navy-800"><span className="font-mono text-xs text-signal-500">0{index+1}</span><PillarIcon aria-hidden="true" className="mt-10 text-steel-300" size={29}/><h3 className="mt-8 text-xl font-semibold">{title as string}</h3><p className="mt-4 text-sm leading-6 text-steel-300">{copy as string}</p></Reveal>})}</div></div></section>

      <section className="bg-paper-50 py-20 md:py-32"><div className="container-shell grid gap-12 lg:grid-cols-2 lg:gap-16"><Reveal className="relative min-h-[34rem] overflow-hidden rounded-3xl"><Image src="/images/industries/energy-utilities.png" alt="Solar generation and utility infrastructure illustrating resource transition" fill sizes="(min-width:1024px) 50vw,100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-ink-950/75 via-transparent to-transparent"/><div className="absolute bottom-7 left-7 right-7 text-white"><p className="eyebrow text-signal-500">Measure within a boundary</p><p className="mt-4 max-w-md text-2xl font-semibold">Know what the number includes before deciding what it means.</p></div></Reveal><Reveal delay={.08} className="flex flex-col justify-center"><p className="eyebrow text-signal-600">Measurement discipline</p><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] md:text-5xl">Build the baseline before publishing the target.</h2><p className="mt-7 text-lg leading-8 text-slate-700">A useful environmental measure states the facility or process boundary, time period, data source, calculation method, units, exclusions, responsible owner, and review status.</p><ul className="mt-9 space-y-4 border-t border-ink-950/15 pt-7">{["Define organizational and operational boundaries","Use consistent units and documented source data","Separate absolute totals from normalized intensity","Explain estimates, assumptions, and material exclusions","Review changes in production mix before comparing periods"].map((item)=><li key={item} className="flex items-center gap-3 text-sm font-semibold"><CheckCircle2 aria-hidden="true" className="text-signal-600" size={18}/>{item}</li>)}</ul></Reveal></div></section>

      <section className="bg-mist-100 py-20 md:py-28"><div className="container-shell"><Reveal className="grid gap-8 md:grid-cols-[1fr_.65fr] md:items-end"><div><p className="eyebrow text-signal-600">Operational measures</p><h2 className="mt-6 max-w-5xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Measure decisions, not just ambition.</h2></div><p className="max-w-lg leading-7 text-slate-700">A future Corvex baseline can focus on measures that teams can understand, influence, and verify.</p></Reveal><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[[Sparkles,"Energy","Purchased energy by source, process or facility use, and intensity within a defined boundary."],[Droplets,"Water","Withdrawal, use, discharge, reuse, and local water context where materially relevant."],[Recycle,"Material yield","Input mass, finished output, offcut, recoverable scrap, rework, and loss."],[Boxes,"Packaging","Material type, pack efficiency, damage prevention, reuse, and recovery route."],[Truck,"Logistics","Shipment weight, distance, mode, consolidation, routing, and project sequence."],[ShieldCheck,"Product life","Exposure assumptions, finish, inspection, maintenance, repair, and replacement needs."]].map(([Icon,title,copy],index)=>{const MetricIcon=Icon as typeof Sparkles;return <Reveal key={title as string} delay={(index%3)*.05} className="rounded-2xl border border-ink-950/10 bg-white p-7"><MetricIcon aria-hidden="true" className="text-signal-600" size={27}/><h3 className="mt-9 text-xl font-semibold">{title as string}</h3><p className="mt-4 text-sm leading-6 text-slate-700">{copy as string}</p></Reveal>})}</div></div></section>

      <section className="bg-navy-900 py-20 text-white md:py-28"><div className="container-shell grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-24"><Reveal><Target aria-hidden="true" className="text-signal-500" size={34}/><p className="eyebrow mt-8 text-signal-500">Target-setting logic</p><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] md:text-5xl">Set targets only after the baseline can carry them.</h2></Reveal><Reveal delay={.08}><div className="border-t border-white/15">{[["Define","Choose the metric, boundary, baseline period, units, data owner, and calculation method."],["Understand","Identify the important drivers, constraints, variability, and credible improvement levers."],["Commit","Set a time-bound target with an accountable owner and approved investment or operating plan."],["Measure","Collect consistent source data and review both progress and changes in underlying conditions."],["Correct","Respond when actions do not produce the expected result or data quality is insufficient."],["Report","Publish the result with scope, method, restatements, limitations, and assurance status visible."]].map(([title,copy],index)=><div key={title} className="grid gap-3 border-b border-white/15 py-5 sm:grid-cols-[3rem_.4fr_1fr]"><span className="font-mono text-xs text-signal-500">0{index+1}</span><h3 className="font-semibold">{title}</h3><p className="text-sm leading-6 text-steel-300">{copy}</p></div>)}</div></Reveal></div></section>

      <section className="bg-paper-50 py-20 md:py-28"><div className="container-shell grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:gap-24"><Reveal><p className="eyebrow text-signal-600">Responsible claim checklist</p><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] md:text-5xl">Make environmental language specific enough to test.</h2><p className="mt-6 max-w-sm leading-7 text-slate-700">Broad words such as green, sustainable, eco-friendly, low-carbon, recycled, or recyclable need defined evidence and limitations.</p></Reveal><Reveal delay={.08} className="grid gap-4 sm:grid-cols-2">{[["Subject","Which exact product, material, facility, process, or shipment is covered?"],["Attribute","Which environmental characteristic is being claimed?"],["Boundary","Which lifecycle stages, locations, dates, and exclusions apply?"],["Measure","What unit, method, baseline, data source, and comparison support it?"],["Qualification","What limitations, conditions, tradeoffs, or local dependencies must be stated?"],["Evidence","Is the supporting record current, reviewable, and approved for publication?"]].map(([title,copy],index)=><div key={title} className="rounded-xl border border-ink-950/10 bg-mist-100 p-6"><span className="font-mono text-xs text-signal-600">0{index+1}</span><h3 className="mt-7 font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-700">{copy}</p></div>)}</Reveal></div></section>

      <section className="bg-mist-100 py-16 md:py-20"><div className="container-shell flex gap-5 rounded-2xl border border-ink-950/10 bg-white p-7 md:p-10"><BarChart3 aria-hidden="true" className="mt-1 shrink-0 text-signal-600" size={30}/><div><p className="eyebrow text-signal-600">Current disclosure status</p><h2 className="mt-3 text-2xl font-semibold">No quantified Corvex environmental performance is claimed yet.</h2><p className="mt-3 max-w-4xl text-sm leading-6 text-slate-700">No emissions inventory, renewable-energy share, recycled-content percentage, waste-diversion rate, water reduction, lifecycle assessment, environmental product declaration, net-zero commitment, or third-party environmental certification is presented without an approved baseline and evidence.</p></div></div></section>

      <section className="relative overflow-hidden bg-signal-600 py-24 text-white md:py-32"><div className="container-shell relative grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><Reveal><p className="eyebrow text-white/70">Build responsibility into the brief</p><h2 className="mt-6 max-w-5xl text-5xl font-semibold leading-[1.02] tracking-[-.055em] text-balance md:text-7xl">Define the lifecycle priorities that matter.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/80">Share exposure, service-life intent, material constraints, packaging needs, maintenance approach, logistics plan, and required environmental evidence.</p></Reveal><Reveal delay={.1}><Link className="button border-white bg-white text-ink-950 hover:bg-paper-50" href="/request-a-quote">Discuss lifecycle requirements <ArrowRight aria-hidden="true" size={18}/></Link></Reveal></div></section>
    </>
  );
}
