import type { Metadata } from "next";
import Link from "next/link";
import {
  AlertCircle, ArrowDown, ArrowRight, BadgeCheck, CalendarClock, CheckCircle2,
  ClipboardCheck, ExternalLink, FileCheck2, Fingerprint, SearchCheck, ShieldCheck,
} from "lucide-react";

import { ComplianceNavigator } from "@/sections/certifications/compliance-navigator";
import { Reveal } from "@/sections/home/home-interactions";

export const metadata: Metadata = {
  title: "Certifications & Compliance",
  description: "Understand the Corvex approach to certificate authenticity, scope, validity, product evidence, project quality packs, and procurement documentation.",
  alternates: { canonical: "/certifications" },
  openGraph: { title: "Corvex Certifications & Compliance", description: "A verification-first center for current, scoped, and authentic business and product evidence.", url: "/certifications" },
};

export default function CertificationsPage() {
  return (
    <>
      <section className="relative isolate overflow-hidden bg-ink-950 pb-20 pt-24 text-white md:pb-28 md:pt-36"><div className="industrial-grid absolute inset-0 opacity-50" aria-hidden="true"/><div className="absolute right-[-8rem] top-[-10rem] h-[36rem] w-[36rem] rounded-full border border-signal-500/15" aria-hidden="true"/><div className="container-shell relative"><Reveal><p className="eyebrow text-signal-500">Certifications & compliance</p><h1 className="mt-7 max-w-6xl text-5xl font-semibold leading-[.94] tracking-[-.06em] text-balance md:text-8xl">Evidence should be<br/><span className="text-steel-300">easy to verify.</span></h1></Reveal><Reveal delay={.08} className="mt-12 grid gap-8 border-t border-white/15 pt-8 md:grid-cols-[1fr_auto] md:items-end"><p className="max-w-2xl text-lg leading-8 text-steel-300">A certification is meaningful only when the issuer, entity, location, scope, standard, validity, and current status are clear.</p><a className="inline-flex items-center gap-3 font-mono text-xs uppercase tracking-[.14em] text-steel-300" href="#verification-center"><ArrowDown aria-hidden="true" className="text-signal-500" size={18}/> Explore verification</a></Reveal></div></section>

      <section className="bg-paper-50 py-20 md:py-28"><div className="container-shell"><Reveal className="rounded-3xl border border-signal-500/25 bg-white p-7 shadow-[0_18px_55px_rgba(8,17,28,.07)] md:p-10"><div className="grid gap-8 md:grid-cols-[auto_1fr_auto] md:items-center"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-signal-600 text-white"><AlertCircle aria-hidden="true" size={27}/></span><div><p className="eyebrow text-signal-600">Public evidence status</p><h2 className="mt-3 text-2xl font-semibold md:text-3xl">No verified Corvex certificates are currently published.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">This is an intentional integrity safeguard. Approved records can be added when the source document, current validity, scope, and publication permission are confirmed.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-mist-100 px-4 py-2 font-mono text-xs text-slate-700"><span className="h-2 w-2 rounded-full bg-signal-500"/> Awaiting evidence</span></div></Reveal></div></section>

      <section className="bg-mist-100 py-20 md:py-28"><div className="container-shell grid gap-12 lg:grid-cols-[.65fr_1.35fr] lg:gap-24"><Reveal><p className="eyebrow text-signal-600">Verification before display</p><SearchCheck aria-hidden="true" className="mt-8 text-signal-600" size={39}/></Reveal><Reveal delay={.08}><h2 className="text-4xl font-semibold leading-[1.08] tracking-[-.05em] md:text-6xl">A logo alone is not proof of certification.</h2><p className="mt-8 max-w-4xl text-xl leading-9 text-slate-700">Every published record should connect the exact Corvex legal entity and covered location to a named issuer, defined scope, referenced standard or scheme, issue status, validity period, and—where available—a public verification route.</p></Reveal></div></section>

      <section id="verification-center" className="scroll-mt-24 bg-paper-50 py-20 md:py-28"><div className="container-shell"><Reveal className="grid gap-8 md:grid-cols-[1fr_.65fr] md:items-end"><div><p className="eyebrow text-signal-600">Document navigator</p><h2 className="mt-6 max-w-5xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Know what each document actually proves.</h2></div><p className="max-w-lg leading-7 text-slate-700">Explore six evidence categories, their intended purpose, common document types, and essential verification points.</p></Reveal><div className="mt-14"><ComplianceNavigator/></div></div></section>

      <section className="bg-ink-950 py-20 text-white md:py-28"><div className="container-shell"><Reveal><p className="eyebrow text-signal-500">Certificate verification checklist</p><h2 className="mt-6 max-w-5xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Read the record beyond the badge.</h2></Reveal><div className="mt-14 grid gap-px overflow-hidden rounded-2xl bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{[[Fingerprint,"Entity","Does the legal name on the document match the company you are evaluating?"],[BadgeCheck,"Scope","Which activity, product, service, facility, or management system is actually covered?"],[CalendarClock,"Validity","Are issue, expiry, surveillance, suspension, and current status understood?"],[ExternalLink,"Authenticity","Can the issuer, accreditation context, certificate number, or public register be checked?"],[FileCheck2,"Standard","Is the exact standard, scheme, edition, or technical basis stated?"],[ClipboardCheck,"Location","Which manufacturing site, office, or organizational boundary is included?"],[SearchCheck,"Limitations","Are exclusions, conditions, annexures, and referenced schedules available?"],[ShieldCheck,"Currency","Is the displayed file the latest approved public revision?"]].map(([Icon,title,copy],index)=>{const VerifyIcon=Icon as typeof Fingerprint;return <Reveal key={title as string} delay={(index%4)*.04} className="group bg-ink-950 p-7 transition-colors hover:bg-navy-800"><span className="font-mono text-xs text-signal-500">0{index+1}</span><VerifyIcon aria-hidden="true" className="mt-10 text-steel-300" size={27}/><h3 className="mt-7 text-xl font-semibold">{title as string}</h3><p className="mt-4 text-sm leading-6 text-steel-300">{copy as string}</p></Reveal>})}</div></div></section>

      <section className="bg-mist-100 py-20 md:py-28"><div className="container-shell grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-24"><Reveal><p className="eyebrow text-signal-600">Publication workflow</p><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] md:text-5xl">From source file to trusted public record.</h2><p className="mt-6 max-w-sm leading-7 text-slate-700">Published evidence should remain controlled throughout its online lifecycle.</p></Reveal><Reveal delay={.08}><div className="border-t border-ink-950/15">{[["Receive","Obtain the complete source document from an authorized internal owner."],["Authenticate","Check issuer, certificate or report reference, entity, site, scope, and public registry where available."],["Review","Confirm validity, publication permission, confidential information, and relevant annexures."],["Publish","Display the current file with a structured summary, issue data, scope, and verification link."],["Monitor","Track expiry, surveillance, replacement, suspension, withdrawal, and changed scope."],["Archive","Remove superseded public files while retaining controlled internal history as required."]].map(([title,copy],index)=><div key={title} className="grid gap-3 border-b border-ink-950/15 py-5 sm:grid-cols-[3rem_.4fr_1fr]"><span className="font-mono text-xs text-signal-600">0{index+1}</span><h3 className="font-semibold">{title}</h3><p className="text-sm leading-6 text-slate-700">{copy}</p></div>)}</div></Reveal></div></section>

      <section className="bg-paper-50 py-20 md:py-28"><div className="container-shell"><Reveal className="grid gap-8 md:grid-cols-[1fr_.65fr] md:items-end"><div><p className="eyebrow text-signal-600">Procurement-ready evidence</p><h2 className="mt-6 max-w-5xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Build the pack around the requirement.</h2></div><p className="max-w-lg leading-7 text-slate-700">A tender or vendor review should receive the relevant current evidence—not a generic folder of unrelated badges and expired documents.</p></Reveal><div className="mt-14 grid gap-4 md:grid-cols-3">{[["01","Map the clause","Connect every requested eligibility or technical clause to a responsible owner and source record."],["02","Check the fit","Confirm entity, site, product, scope, standard, date, and required format before submission."],["03","State the gap","Identify unavailable evidence, exceptions, or pending renewal rather than implying compliance."],["04","Control the issue","Use the current approved revision, authorized signatory, and consistent company information."],["05","Protect sensitive data","Share confidential commercial or personal information only through the approved channel."],["06","Retain the submission","Keep a controlled record of what was submitted, when, to whom, and against which requirement."]].map(([number,title,copy])=><div key={number} className="rounded-2xl border border-ink-950/10 bg-mist-100 p-7"><span className="font-mono text-xs text-signal-600">{number}</span><h3 className="mt-9 text-xl font-semibold">{title}</h3><p className="mt-4 text-sm leading-6 text-slate-700">{copy}</p></div>)}</div></div></section>

      <section className="bg-navy-900 py-16 text-white md:py-20"><div className="container-shell flex flex-col gap-7 rounded-2xl border border-white/10 bg-white/[.04] p-7 md:flex-row md:items-center md:justify-between md:p-10"><div className="flex gap-5"><CheckCircle2 aria-hidden="true" className="mt-1 shrink-0 text-signal-500" size={29}/><div><p className="eyebrow text-signal-500">Integrity statement</p><h2 className="mt-3 text-2xl font-semibold">No certification claim is inferred from this framework.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-steel-300">The categories and verification guidance describe how evidence should be assessed. They do not state that Corvex currently holds any particular registration, ISO certificate, product approval, test report, accreditation, or tender eligibility.</p></div></div></div></section>

      <section className="relative overflow-hidden bg-signal-600 py-24 text-white md:py-32"><div className="container-shell relative grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><Reveal><p className="eyebrow text-white/70">Need evidence for a procurement review?</p><h2 className="mt-6 max-w-5xl text-5xl font-semibold leading-[1.02] tracking-[-.055em] text-balance md:text-7xl">Start with the exact requirement.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/80">Share the tender clause, product, project, entity, validity period, and submission format so the appropriate verified document set can be identified.</p></Reveal><Reveal delay={.1}><Link className="button border-white bg-white text-ink-950 hover:bg-paper-50" href="/contact">Request document review <ArrowRight aria-hidden="true" size={18}/></Link></Reveal></div></section>
    </>
  );
}
