import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import {
  AlertTriangle, ArrowDown, ArrowRight, CheckCircle2, ClipboardCheck, FileCheck2,
  Fingerprint, Gauge, History, ScanLine, ShieldCheck, Target, Wrench,
} from "lucide-react";

import { QualityMatrix } from "@/sections/quality/quality-matrix";
import { Reveal } from "@/sections/home/home-interactions";

export const metadata: Metadata = {
  title: "Quality Assurance",
  description: "Explore the Corvex quality framework for incoming material, in-process control, inspection, traceability, nonconformance, release, and project documentation.",
  alternates: { canonical: "/quality-assurance" },
  openGraph: { title: "Corvex Quality Assurance", description: "Quality decisions made visible from product definition through dispatch release.", url: "/quality-assurance" },
};

export default function QualityAssurancePage() {
  return (
    <>
      <section className="relative isolate min-h-[calc(100svh-5rem)] overflow-hidden bg-ink-950 text-white">
        <Image src="/images/home/manufacturing-floor.png" alt="Engineer visually inspecting precision steel mesh during production" fill priority sizes="100vw" className="object-cover" />
        <div className="absolute inset-0 bg-[linear-gradient(90deg,#08111c_0%,rgba(8,17,28,.92)_43%,rgba(8,17,28,.26)_82%),linear-gradient(to_top,#08111c_0%,transparent_50%)]" />
        <div className="industrial-grid absolute inset-0 opacity-25" aria-hidden="true" />
        <div className="container-shell relative flex min-h-[calc(100svh-5rem)] flex-col justify-between pb-10 pt-20 md:pt-28"><Reveal><p className="eyebrow text-signal-500">Quality assurance</p><h1 className="mt-7 max-w-6xl text-[clamp(3.5rem,8vw,8rem)] font-semibold leading-[.91] tracking-[-.065em] text-balance">Evidence at<br/><span className="text-steel-300">every handoff.</span></h1></Reveal><Reveal delay={.08} className="grid gap-8 border-t border-white/15 pt-8 md:grid-cols-[1fr_auto] md:items-end"><p className="max-w-2xl text-lg leading-8 text-steel-300">A quality system should make the requirement, status, decision, and supporting evidence easier to follow—from incoming material to dispatch release.</p><a className="inline-flex items-center gap-3 font-mono text-xs uppercase tracking-[.14em] text-steel-300" href="#quality-journey"><ArrowDown aria-hidden="true" className="text-signal-500" size={18}/> Follow the evidence</a></Reveal></div>
      </section>

      <section className="bg-paper-50 py-20 md:py-32"><div className="container-shell grid gap-12 lg:grid-cols-[.65fr_1.35fr] lg:gap-24"><Reveal><p className="eyebrow text-signal-600">Our quality position</p><Target aria-hidden="true" className="mt-8 text-signal-600" size={38}/></Reveal><Reveal delay={.08}><h2 className="text-4xl font-semibold leading-[1.08] tracking-[-.05em] md:text-6xl">Inspection finds outcomes. Quality assurance shapes them.</h2><p className="mt-8 max-w-4xl text-xl leading-9 text-slate-700">The strongest quality decisions happen before a product reaches final inspection: in clear definition, verified inputs, capable process settings, useful checkpoints, controlled status, and timely response when something differs.</p></Reveal></div></section>

      <section id="quality-journey" className="scroll-mt-24 bg-mist-100 py-20 md:py-28"><div className="container-shell"><Reveal className="grid gap-8 md:grid-cols-[1fr_.65fr] md:items-end"><div><p className="eyebrow text-signal-600">Interactive quality matrix</p><h2 className="mt-6 max-w-5xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Connect each characteristic to a decision.</h2></div><p className="max-w-lg leading-7 text-slate-700">Explore typical checks and the evidence they should create. Exact inspection criteria remain product- and project-specific.</p></Reveal><div className="mt-14"><QualityMatrix/></div></div></section>

      <section className="bg-ink-950 py-20 text-white md:py-28"><div className="container-shell"><Reveal><p className="eyebrow text-signal-500">Five quality gates</p><h2 className="mt-6 max-w-5xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Place control where it can influence the result.</h2></Reveal><div className="mt-14 grid gap-px overflow-hidden rounded-2xl bg-white/10 sm:grid-cols-2 lg:grid-cols-5">{[["01","Definition","Approved requirements establish what acceptance means."],["02","Incoming","Material status is decided before production use."],["03","First piece","Initial output validates setup before continued production."],["04","In process","Checks monitor characteristics while correction remains practical."],["05","Final release","Configuration, condition, quantity, identity, and records close the loop."]].map(([number,title,copy])=><div key={number} className="group bg-ink-950 p-7 transition-colors hover:bg-navy-800"><span className="font-mono text-xs text-signal-500">{number}</span><h3 className="mt-12 text-xl font-semibold">{title}</h3><p className="mt-4 text-sm leading-6 text-steel-300">{copy}</p></div>)}</div></div></section>

      <section className="bg-paper-50 py-20 md:py-28"><div className="container-shell grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-24"><Reveal><p className="eyebrow text-signal-600">Measurement confidence</p><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] md:text-5xl">Use the right measurement for the decision.</h2><p className="mt-6 max-w-sm leading-7 text-slate-700">A number is useful only when the method, instrument, resolution, condition, and acceptance requirement are understood.</p></Reveal><Reveal delay={.08} className="grid gap-4 sm:grid-cols-2">{[[Gauge,"Fit for purpose","Select measurement resources appropriate to the characteristic and required resolution."],[History,"Known status","Keep calibration or verification status visible before equipment is used for acceptance."],[Wrench,"Protected condition","Store, handle, maintain, and check instruments so condition does not undermine the result."],[ClipboardCheck,"Recorded context","Capture the result with enough product, stage, method, and status context to remain useful."]].map(([Icon,title,copy])=>{const MeasureIcon=Icon as typeof Gauge;return <div key={title as string} className="rounded-2xl border border-ink-950/10 bg-mist-100 p-7"><MeasureIcon aria-hidden="true" className="text-signal-600" size={27}/><h3 className="mt-8 text-xl font-semibold">{title as string}</h3><p className="mt-4 text-sm leading-6 text-slate-700">{copy as string}</p></div>})}</Reveal></div></section>

      <section className="bg-mist-100 py-20 md:py-28"><div className="container-shell"><Reveal className="grid gap-8 md:grid-cols-[1fr_.65fr] md:items-end"><div><p className="eyebrow text-signal-600">Traceability</p><h2 className="mt-6 max-w-5xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Connect the product to its quality story.</h2></div><p className="max-w-lg leading-7 text-slate-700">Traceability depth should match the product, project, risk, and agreed documentation requirement.</p></Reveal><div className="mt-14 grid gap-4 md:grid-cols-4">{[[Fingerprint,"Identity","Product, variant, project, batch, or package context."],[ScanLine,"Process","Relevant production stage and inspection status."],[CheckCircle2,"Decision","Accepted, hold, rework, rejected, or released status."],[FileCheck2,"Evidence","Records required to support the agreed release."]].map(([Icon,title,copy],index)=>{const TraceIcon=Icon as typeof Fingerprint;return <Reveal key={title as string} delay={index*.05} className="rounded-2xl border border-ink-950/10 bg-white p-7"><span className="font-mono text-xs text-signal-600">0{index+1}</span><TraceIcon aria-hidden="true" className="mt-10 text-signal-600" size={27}/><h3 className="mt-7 text-xl font-semibold">{title as string}</h3><p className="mt-4 text-sm leading-6 text-slate-700">{copy as string}</p></Reveal>})}</div></div></section>

      <section className="bg-navy-900 py-20 text-white md:py-28"><div className="container-shell grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-24"><Reveal><AlertTriangle aria-hidden="true" className="text-signal-500" size={34}/><p className="eyebrow mt-8 text-signal-500">When something differs</p><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] md:text-5xl">Contain first. Decide clearly. Learn deliberately.</h2></Reveal><Reveal delay={.08}><div className="border-t border-white/15">{[["Identify","Make the nonconforming status visible and prevent unintended use."],["Contain","Separate affected material and understand the possible extent."],["Evaluate","Compare the condition with the requirement and assess consequences."],["Dispose","Authorize rework, acceptance under approved concession, return, or rejection."],["Verify","Check completed action before status changes or product is released."],["Improve","Where appropriate, address recurring causes and update controls."]].map(([title,copy],index)=><div key={title} className="grid gap-3 border-b border-white/15 py-5 sm:grid-cols-[3rem_.45fr_1fr]"><span className="font-mono text-xs text-signal-500">0{index+1}</span><h3 className="font-semibold">{title}</h3><p className="text-sm leading-6 text-steel-300">{copy}</p></div>)}</div></Reveal></div></section>

      <section className="bg-paper-50 py-20 md:py-28"><div className="container-shell grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:gap-24"><Reveal><p className="eyebrow text-signal-600">Project quality pack</p><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] md:text-5xl">Documents aligned with the confirmed scope.</h2><p className="mt-6 max-w-sm leading-7 text-slate-700">The appropriate pack depends on product configuration, contract, inspection plan, and agreed submittal requirements.</p></Reveal><Reveal delay={.08} className="grid gap-4 sm:grid-cols-2">{[["Product schedule","Controlled configuration and acceptance characteristics."],["Inspection plan","Agreed stages, checks, responsibilities, and record needs."],["Material evidence","Applicable identity or supplier documentation where required."],["Inspection records","Results generated through defined incoming, process, or final checks."],["Release evidence","Authorization that agreed release criteria have been addressed."],["Packing information","Package identity, quantity, product protection, and dispatch context."]].map(([title,copy],index)=><div key={title} className="group rounded-xl border border-ink-950/10 bg-mist-100 p-6 transition hover:border-signal-500/40"><div className="flex items-start justify-between"><span className="font-mono text-xs text-signal-600">0{index+1}</span><FileCheck2 aria-hidden="true" className="text-slate-500" size={20}/></div><h3 className="mt-7 font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-700">{copy}</p></div>)}</Reveal></div></section>

      <section className="bg-mist-100 py-16 md:py-20"><div className="container-shell flex flex-col gap-6 rounded-2xl border border-ink-950/10 bg-white p-7 md:flex-row md:items-center md:justify-between md:p-10"><div className="flex gap-5"><ShieldCheck aria-hidden="true" className="mt-1 shrink-0 text-signal-600" size={29}/><div><h2 className="text-2xl font-semibold">Certification and standards require verified evidence.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">No ISO certificate, product standard compliance, test result, accreditation, or regulatory approval is claimed on this page. Those references should be published only from current, approved Corvex documents with scope and validity confirmed.</p></div></div><Link className="inline-flex shrink-0 items-center gap-2 text-sm font-semibold text-signal-600" href="/certifications">Certification center <ArrowRight aria-hidden="true" size={17}/></Link></div></section>

      <section className="relative overflow-hidden bg-signal-600 py-24 text-white md:py-32"><div className="container-shell relative grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><Reveal><p className="eyebrow text-white/70">Define quality with the project</p><h2 className="mt-6 max-w-5xl text-5xl font-semibold leading-[1.02] tracking-[-.055em] text-balance md:text-7xl">Make acceptance clear before production begins.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/80">Share the product schedule, governing documents, inspection needs, hold points, and release records required for the scope.</p></Reveal><Reveal delay={.1}><Link className="button border-white bg-white text-ink-950 hover:bg-paper-50" href="/request-a-quote">Discuss quality requirements <ArrowRight aria-hidden="true" size={18}/></Link></Reveal></div></section>
    </>
  );
}
