export type InsightCategory = "Specification" | "Materials" | "Project Planning" | "Quality" | "Lifecycle";

export type Insight = {
  slug: string; title: string; excerpt: string; category: InsightCategory; publishedAt: string;
  readingTime: string; image: string; alt: string; author: string;
  sections: Array<{ heading: string; paragraphs: string[]; bullets?: string[] }>;
  related: string[];
};

export const insightCategories: Array<"All" | InsightCategory> = ["All", "Specification", "Materials", "Project Planning", "Quality", "Lifecycle"];

export const insights: Insight[] = [
  {
    slug: "seven-inputs-reliable-perimeter-specification", title: "Seven inputs that shape a reliable perimeter specification",
    excerpt: "Move beyond product names by defining the site, operating need, interfaces, exposure, lifecycle, delivery, and evidence first.",
    category: "Specification", publishedAt: "2026-07-22", readingTime: "7 min read", image: "/images/industries/critical-infrastructure.png", alt: "Critical utility site with a controlled perimeter", author: "Corvex Editorial Team",
    sections: [
      { heading: "Start with the operating outcome", paragraphs: ["A useful perimeter specification begins by defining what the boundary must do in its operating context. Demarcation, delay, visibility, privacy, access control, animal management, and monitoring readiness are different outcomes, even when they use similar materials.", "Write the intended outcome before naming a mesh, wire, coil, or post. This makes later product decisions easier to justify and compare."], bullets: ["Required boundary function", "Users and legitimate access", "Threat or intrusion context", "Response after a boundary event"] },
      { heading: "Capture the physical interfaces", paragraphs: ["Terrain, soil, drainage, walls, gates, roads, buildings, utilities, vegetation, and neighboring public space all influence the assembly. A repeated typical detail rarely remains typical across an entire site.", "Mark transitions and interfaces on the boundary plan. They are common sources of ambiguity, rework, gaps, and commercial exclusions."], bullets: ["Changes in level and alignment", "Gate and corner conditions", "Civil foundation strategy", "Crossings, culverts, and existing structures"] },
      { heading: "Define exposure, delivery, and evidence", paragraphs: ["Material and finish should reflect the exposure and intended maintenance approach. Delivery quantities and packaging should reflect site sequence. Inspection and documentation should reflect product risk and contract needs.", "The strongest specification connects all seven inputs: outcome, site, interfaces, exposure, access, delivery, and evidence. Product dimensions then sit inside a coherent system rather than an isolated schedule."], bullets: ["Environmental exposure", "Service and maintenance expectations", "Release and delivery sequence", "Required submittals and acceptance evidence"] },
    ], related: ["galvanized-or-stainless-selection", "perimeter-civil-access-interfaces", "inspection-plan-before-production"],
  },
  {
    slug: "galvanized-or-stainless-selection", title: "Galvanized or stainless: selecting for exposure and service conditions",
    excerpt: "A practical material-selection framework based on environment, fabrication, maintenance, appearance, and lifecycle—not labels alone.",
    category: "Materials", publishedAt: "2026-07-10", readingTime: "8 min read", image: "/images/products/concertina-coil.png", alt: "Detailed galvanized steel concertina barrier coil", author: "Corvex Editorial Team",
    sections: [
      { heading: "Material choice begins with exposure", paragraphs: ["Galvanized and stainless steel are families of materials and finishes, not single performance levels. The relevant question is how a defined material and finish behave in the actual atmosphere, moisture, contamination, temperature, contact, and maintenance context.", "Coastal salts, industrial pollutants, standing water, soil contact, chemical exposure, and trapped debris can change the expected corrosion mechanism. Site classification and detail design should be reviewed together."], bullets: ["Atmospheric and local exposure", "Wet and dry cycling", "Dissimilar-material contact", "Crevices, cut edges, and water traps"] },
      { heading: "Fabrication and handling affect the finish", paragraphs: ["Forming, cutting, welding, drilling, transport, and installation can influence surface condition. The finish strategy must account for the full production sequence and any permitted repair method.", "Stainless selection also requires attention to grade, surface contamination, fabrication practice, and cleaning. A stainless label does not eliminate the need for process discipline."], bullets: ["Finish before or after fabrication", "Tool and handling contamination", "Repair of damaged areas", "Packaging and installation protection"] },
      { heading: "Compare lifecycle scenarios", paragraphs: ["A useful comparison considers acquisition, installation, inspection, cleaning, repair, replacement, appearance, downtime, and recovery. The lowest initial material cost may not produce the lowest lifecycle burden, while a higher-grade material may be unnecessary in a mild, maintainable environment.", "Document the assumptions behind the selection so future teams understand the intended exposure and care conditions."], bullets: ["Target service condition", "Inspection access and frequency", "Replacement consequence", "Availability of suitable maintenance"] },
    ], related: ["seven-inputs-reliable-perimeter-specification", "designing-for-maintainable-perimeters", "inspection-plan-before-production"],
  },
  {
    slug: "perimeter-civil-access-interfaces", title: "Where perimeter packages interface with civil and access works",
    excerpt: "Resolve foundations, gates, drainage, levels, utilities, and temporary works before they become site conflicts.",
    category: "Project Planning", publishedAt: "2026-06-26", readingTime: "6 min read", image: "/images/industries/transport-logistics.png", alt: "Transport and logistics terminal with long controlled boundary", author: "Corvex Editorial Team",
    sections: [
      { heading: "The boundary is a chain of interfaces", paragraphs: ["Fence fabric and barrier products rarely fail as isolated ideas; difficulty often appears where the perimeter meets foundations, walls, gates, roads, slopes, drainage, utilities, or another contractor's package.", "Create an interface register early. Assign design input, approval, supply, installation, inspection, and handover responsibility for every recurring transition."], bullets: ["Post-to-foundation connection", "Fence-to-wall termination", "Gate and access-control boundary", "Temporary-to-permanent works"] },
      { heading: "Civil information controls geometry", paragraphs: ["Post length, spacing, base condition, stepping, grading, and bottom clearance depend on surveyed levels and civil details. Late changes can alter material quantity, prefabricated components, and installation sequence.", "Coordinate drainage and erosion paths so the boundary does not create unintended blockage or exposed gaps after weather events."], bullets: ["Surveyed alignment and levels", "Foundation type and design responsibility", "Drainage and crossing details", "Tolerance and adjustment strategy"] },
      { heading: "Gates need operational information", paragraphs: ["A gate is both a structural opening and an operational control point. Vehicle envelope, frequency, queueing, emergency access, automation, power, safety devices, security zoning, and manual override all influence the surrounding perimeter.", "Freeze gate interfaces only after stakeholders agree how the opening will be used, controlled, maintained, and handed over."], bullets: ["Clear opening and vehicle path", "Operating frequency and control", "Power and data interfaces", "Safety, emergency, and maintenance access"] },
    ], related: ["seven-inputs-reliable-perimeter-specification", "long-run-boundary-planning", "designing-for-maintainable-perimeters"],
  },
  {
    slug: "inspection-plan-before-production", title: "Why the inspection plan belongs before production",
    excerpt: "Place checks where they can influence the outcome and connect every result to a clear acceptance decision.",
    category: "Quality", publishedAt: "2026-06-12", readingTime: "7 min read", image: "/images/home/manufacturing-floor.png", alt: "Engineer inspecting steel mesh during controlled production", author: "Corvex Editorial Team",
    sections: [
      { heading: "Acceptance must be understood before work begins", paragraphs: ["An inspection plan translates a product definition into stages, characteristics, methods, responsibilities, frequency, records, and decision points. Creating it after production turns quality into a search for evidence that may no longer be available.", "Start with characteristics that influence fit, function, assembly, finish, quantity, identity, and contractual release."], bullets: ["Requirement and acceptance source", "Stage where the check is most useful", "Method and measurement resource", "Responsible decision and record"] },
      { heading: "Not every check belongs at the end", paragraphs: ["Material identity belongs before use. Setup-sensitive geometry belongs at first-piece approval. Stable process characteristics may be monitored during production. Packaging and quantity belong close to dispatch.", "Placing checks near the decision shortens feedback, limits affected quantity, and makes corrective action more practical."], bullets: ["Incoming material gate", "First-piece or setup gate", "In-process monitoring", "Final configuration and dispatch release"] },
      { heading: "Plan the response as well as the check", paragraphs: ["A result without a defined response creates delay and inconsistent decisions. The inspection plan should connect acceptance, hold, rework, concession, rejection, reinspection, and release authority.", "Project hold and witness points also require realistic notification, access, evidence, and schedule allowances."], bullets: ["Status identification and segregation", "Disposition authority", "Reinspection after action", "Client or third-party participation"] },
    ], related: ["seven-inputs-reliable-perimeter-specification", "galvanized-or-stainless-selection", "designing-for-maintainable-perimeters"],
  },
  {
    slug: "designing-for-maintainable-perimeters", title: "Designing perimeter systems that remain maintainable",
    excerpt: "Make inspection, access, repair, replacement, vegetation control, and records part of the design—not an afterthought.",
    category: "Lifecycle", publishedAt: "2026-05-28", readingTime: "6 min read", image: "/images/industries/data-manufacturing.png", alt: "Modern industrial campus with accessible architectural perimeter", author: "Corvex Editorial Team",
    sections: [
      { heading: "Maintenance begins in the layout", paragraphs: ["Inspection teams need physical access, sightlines, safe working space, and a way to identify changes. Dense vegetation, inaccessible outer faces, uncontrolled drainage, and hidden connections can turn a simple review into a major task.", "Define inspection routes and access conditions alongside the original perimeter alignment."], bullets: ["Clear zones and inspection paths", "Safe access to both faces where required", "Visible connections and status", "Vegetation and drainage management"] },
      { heading: "Design repair boundaries", paragraphs: ["Modular panels, replaceable wires, accessible fixings, repeatable post centers, and documented components can limit the extent of repair. Continuous assemblies may be appropriate, but their repair method should still be understood.", "Keep compatible spare components and controlled technical information proportionate to the consequence of downtime."], bullets: ["Replaceable damage zones", "Accessible fasteners and tensioning", "Compatible component identification", "Temporary security during repair"] },
      { heading: "Maintain the security intent", paragraphs: ["A repaired boundary should recover its intended function, not merely its appearance. The repair process may need temporary controls, inspection, updated records, and confirmation that monitoring or access interfaces remain operational.", "Maintenance planning is part of lifecycle security, cost, safety, and sustainability."], bullets: ["Defined repair acceptance", "Temporary protection strategy", "Post-repair inspection", "Updated asset and maintenance record"] },
    ], related: ["galvanized-or-stainless-selection", "perimeter-civil-access-interfaces", "long-run-boundary-planning"],
  },
  {
    slug: "long-run-boundary-planning", title: "Planning long-run boundaries without repeating the same mistake",
    excerpt: "Use segmentation, transition details, control points, and release planning to manage variation across large perimeters.",
    category: "Project Planning", publishedAt: "2026-05-14", readingTime: "7 min read", image: "/images/industries/energy-utilities.png", alt: "Large remote infrastructure site showing varied boundary conditions", author: "Corvex Editorial Team",
    sections: [
      { heading: "Divide length into meaningful segments", paragraphs: ["A long boundary crosses changing terrain, exposure, ownership, access, construction status, and risk. Treating it as one repeated detail hides the transitions that drive complexity.", "Segment by physical and operating condition, then define which detail, product, foundation, and release logic applies to each section."], bullets: ["Terrain and level band", "Exposure and material zone", "Security and access zone", "Construction and handover phase"] },
      { heading: "Control points anchor the sequence", paragraphs: ["Corners, gates, strainers, changes in direction, ends, walls, crossings, and temporary interfaces are control points. Their location influences setting out, tensioning, prefabrication, quantity, and installation sequence.", "Confirm control points before optimizing repeated intermediate spacing."], bullets: ["Survey and coordinate references", "Structural control locations", "Tolerance accumulation", "Interface approval status"] },
      { heading: "Release in buildable packages", paragraphs: ["Procurement and production releases should reflect approved segments, site readiness, installation sequence, storage space, and risk of late interface change. A single bulk release can create avoidable rework or material handling.", "Package labels and records should let site teams connect delivered material to the intended boundary segment."], bullets: ["Design-release maturity", "Site and civil readiness", "Pack-to-segment identification", "Controlled change after release"] },
    ], related: ["perimeter-civil-access-interfaces", "seven-inputs-reliable-perimeter-specification", "designing-for-maintainable-perimeters"],
  },
];

export function getInsight(slug: string) { return insights.find((insight) => insight.slug === slug); }
