import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import {
  ArrowDown, ArrowRight, Box, BrainCircuit, Compass, Factory,
  FileCheck2, FlaskConical, Gauge, Lightbulb, RefreshCw, ScanLine, Settings2,
} from "lucide-react";

import { InnovationPipeline } from "@/sections/research-development/innovation-pipeline";
import { Reveal } from "@/sections/home/home-interactions";

export const metadata: Metadata = {
  title: "Research & Development",
  description: "Explore the Corvex innovation framework for problem framing, concept engineering, prototyping, validation, industrialization, and controlled improvement.",
  alternates: { canonical: "/research-development" },
  openGraph: { title: "Corvex Research & Development", description: "Turning field constraints into controlled, production-ready steel wire and perimeter solutions.", url: "/research-development" },
};

export default function ResearchDevelopmentPage() {
  return (
    <>
      <section className="relative isolate min-h-[calc(100svh-5rem)] overflow-hidden bg-ink-950 text-white"><Image src="/images/research-development/engineering-lab.png" alt="Corvex engineers evaluating a precision steel mesh prototype in an industrial development lab" fill priority sizes="100vw" className="object-cover object-[62%_center]"/><div className="absolute inset-0 bg-[linear-gradient(90deg,#08111c_0%,rgba(8,17,28,.92)_40%,rgba(8,17,28,.2)_82%),linear-gradient(to_top,#08111c_0%,transparent_48%)]"/><div className="industrial-grid absolute inset-0 opacity-20" aria-hidden="true"/><div className="container-shell relative flex min-h-[calc(100svh-5rem)] flex-col justify-between pb-10 pt-20 md:pt-28"><Reveal><p className="eyebrow text-signal-500">Research & development</p><h1 className="mt-7 max-w-6xl text-[clamp(3.5rem,8vw,8rem)] font-semibold leading-[.91] tracking-[-.065em] text-balance">Question the constraint.<br/><span className="text-steel-300">Engineer the answer.</span></h1></Reveal><Reveal delay={.08} className="grid gap-8 border-t border-white/15 pt-8 md:grid-cols-[1fr_auto] md:items-end"><p className="max-w-2xl text-lg leading-8 text-steel-300">A disciplined path from real operating problems to testable concepts, controlled evidence, and production-ready definitions.</p><a className="inline-flex items-center gap-3 font-mono text-xs uppercase tracking-[.14em] text-steel-300" href="#pipeline"><ArrowDown aria-hidden="true" className="text-signal-500" size={18}/> Explore the pipeline</a></Reveal></div></section>

      <section className="bg-paper-50 py-20 md:py-32"><div className="container-shell grid gap-12 lg:grid-cols-[.65fr_1.35fr] lg:gap-24"><Reveal><p className="eyebrow text-signal-600">Our development position</p><BrainCircuit aria-hidden="true" className="mt-8 text-signal-600" size={39}/></Reveal><Reveal delay={.08}><h2 className="text-4xl font-semibold leading-[1.08] tracking-[-.05em] md:text-6xl">Innovation earns value when it survives the factory and the field.</h2><p className="mt-8 max-w-4xl text-xl leading-9 text-slate-700">A compelling idea is only the beginning. It must be manufacturable, inspectable, installable, maintainable, safe in context, commercially intelligible, and supported by evidence proportionate to its intended use.</p></Reveal></div></section>

      <section id="pipeline" className="scroll-mt-24 bg-mist-100 py-20 md:py-28"><div className="container-shell"><Reveal className="grid gap-8 md:grid-cols-[1fr_.65fr] md:items-end"><div><p className="eyebrow text-signal-600">Interactive development pipeline</p><h2 className="mt-6 max-w-5xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Seven gates from need to learning.</h2></div><p className="max-w-lg leading-7 text-slate-700">Select each stage to examine its decision questions, required thinking, and controlled output.</p></Reveal><div className="mt-14"><InnovationPipeline/></div></div></section>

      <section className="bg-ink-950 py-20 text-white md:py-28"><div className="container-shell"><Reveal><p className="eyebrow text-signal-500">Where development starts</p><h2 className="mt-6 max-w-5xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Useful innovation begins with observable friction.</h2></Reveal><div className="mt-14 grid gap-px overflow-hidden rounded-2xl bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{[[Compass,"Site constraints","Terrain, exposure, space, interfaces, access, and operating conditions."],[RefreshCw,"Recurring problems","Installation difficulty, repair patterns, inconsistent outcomes, or avoidable waste."],[Lightbulb,"New applications","A changing threat, user need, monitoring interface, or construction method."],[Gauge,"Performance gaps","A characteristic that can be defined, compared, and improved with evidence."]].map(([Icon,title,copy],index)=>{const SourceIcon=Icon as typeof Compass;return <Reveal key={title as string} delay={index*.05} className="group bg-ink-950 p-8 transition-colors hover:bg-navy-800"><span className="font-mono text-xs text-signal-500">0{index+1}</span><SourceIcon aria-hidden="true" className="mt-10 text-steel-300" size={29}/><h3 className="mt-8 text-xl font-semibold">{title as string}</h3><p className="mt-4 text-sm leading-6 text-steel-300">{copy as string}</p></Reveal>})}</div></div></section>

      <section className="bg-paper-50 py-20 md:py-32"><div className="container-shell grid gap-12 lg:grid-cols-2 lg:gap-16"><Reveal className="relative min-h-[34rem] overflow-hidden rounded-3xl"><Image src="/images/research-development/engineering-lab.png" alt="Engineers reviewing wire geometry, measurement tools, and prototype samples" fill sizes="(min-width:1024px) 50vw,100vw" className="object-cover object-[66%_center]"/><div className="absolute inset-0 bg-gradient-to-t from-ink-950/75 via-transparent to-transparent"/><div className="absolute bottom-7 left-7 right-7 text-white"><p className="eyebrow text-signal-500">Prototype with purpose</p><p className="mt-4 max-w-md text-2xl font-semibold">Build only what is needed to expose the next uncertainty.</p></div></Reveal><Reveal delay={.08} className="flex flex-col justify-center"><p className="eyebrow text-signal-600">Prototype strategy</p><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] md:text-5xl">Learn earlier, while change is still inexpensive.</h2><p className="mt-7 text-lg leading-8 text-slate-700">A prototype is not automatically a miniature final product. It should represent the geometry, interface, process, or use condition needed to answer a defined question.</p><div className="mt-9 grid gap-4 sm:grid-cols-2">{[[Box,"Form","Physical geometry, fit, handling, and assembly."],[Settings2,"Process","Tooling, setup, manufacturability, and variation."],[ScanLine,"Measurement","Whether critical characteristics can be checked clearly."],[FlaskConical,"Behavior","A controlled approximation of intended use or exposure."]].map(([Icon,title,copy])=>{const PrototypeIcon=Icon as typeof Box;return <div key={title as string} className="border-t border-ink-950/15 pt-5"><PrototypeIcon aria-hidden="true" className="text-signal-600" size={22}/><h3 className="mt-4 font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{copy as string}</p></div>})}</div></Reveal></div></section>

      <section className="bg-mist-100 py-20 md:py-28"><div className="container-shell"><Reveal className="grid gap-8 md:grid-cols-[1fr_.65fr] md:items-end"><div><p className="eyebrow text-signal-600">Validation architecture</p><h2 className="mt-6 max-w-5xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Test the claim—not just the object.</h2></div><p className="max-w-lg leading-7 text-slate-700">Validation starts by defining the intended claim, use boundary, method, acceptance logic, and limitations before interpreting a result.</p></Reveal><div className="mt-14 grid gap-4 md:grid-cols-5">{[["01","Claim","What exactly should the concept do?"],["02","Method","How will the check represent intended use?"],["03","Measure","Which characteristics and results matter?"],["04","Compare","What defines acceptance, improvement, or failure?"],["05","Learn","What limits, surprises, and next actions remain?"]].map(([number,title,copy])=><div key={number} className="rounded-2xl border border-ink-950/10 bg-white p-6"><span className="font-mono text-xs text-signal-600">{number}</span><h3 className="mt-10 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-700">{copy}</p></div>)}</div><p className="mt-7 text-xs leading-5 text-slate-500">No laboratory accreditation, proprietary test capability, patent, validated performance result, or formal R&D facility claim is made without approved Corvex evidence.</p></div></section>

      <section className="bg-navy-900 py-20 text-white md:py-28"><div className="container-shell grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-24"><Reveal><Factory aria-hidden="true" className="text-signal-500" size={34}/><p className="eyebrow mt-8 text-signal-500">Industrialization</p><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] md:text-5xl">A design is not finished until production can control it.</h2></Reveal><Reveal delay={.08} className="grid gap-px overflow-hidden rounded-2xl bg-white/10 sm:grid-cols-2">{[["Product definition","Geometry, material, finish, interfaces, variants, and controlled drawings or schedules."],["Process definition","Tooling, sequence, setup, parameters, handling, and production-stage decisions."],["Quality definition","Critical characteristics, methods, sampling logic, records, and release responsibility."],["Supply definition","Packaging, identification, quantity format, documentation, storage, and dispatch."],["People readiness","Instructions, skills, safety context, escalation, and change awareness."],["Trial evidence","First-piece, pilot production, process learning, and readiness decision."]].map(([title,copy],index)=><div key={title} className="bg-ink-950 p-7"><span className="font-mono text-xs text-signal-500">0{index+1}</span><h3 className="mt-7 text-xl font-semibold">{title}</h3><p className="mt-4 text-sm leading-6 text-steel-300">{copy}</p></div>)}</Reveal></div></section>

      <section className="bg-paper-50 py-20 md:py-28"><div className="container-shell grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:gap-24"><Reveal><p className="eyebrow text-signal-600">Controlled change</p><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] md:text-5xl">Improve without losing the definition.</h2><p className="mt-6 max-w-sm leading-7 text-slate-700">A technically positive change can still create risk when its scope, effect, approval, documentation, or implementation is unclear.</p></Reveal><Reveal delay={.08}><div className="border-t border-ink-950/15">{[["Propose","Describe the reason, intended benefit, affected definition, and supporting evidence."],["Assess","Review product, process, quality, supply, installation, safety, and contractual impact."],["Approve","Assign appropriate technical and commercial authorization before implementation."],["Implement","Update definitions, tools, instructions, records, stock status, and relevant people."],["Verify","Confirm the change achieved its intent without creating unacceptable effects."],["Retain","Capture learning, supersede obsolete information, and preserve decision history."]].map(([title,copy],index)=><div key={title} className="grid gap-3 border-b border-ink-950/15 py-5 sm:grid-cols-[3rem_.4fr_1fr]"><span className="font-mono text-xs text-signal-600">0{index+1}</span><h3 className="font-semibold">{title}</h3><p className="text-sm leading-6 text-slate-700">{copy}</p></div>)}</div></Reveal></div></section>

      <section className="bg-mist-100 py-20 md:py-28"><div className="container-shell"><Reveal><p className="eyebrow text-signal-600">Development outputs</p><h2 className="mt-6 max-w-5xl text-4xl font-semibold tracking-[-.05em] md:text-6xl">Turn learning into usable product knowledge.</h2></Reveal><div className="mt-14 grid gap-4 md:grid-cols-3">{[[FileCheck2,"Development brief","Problem, intended outcome, constraints, success logic, and scope."],[Box,"Prototype definition","What the prototype represents, how it is made, and what it should reveal."],[FlaskConical,"Validation record","Method, conditions, results, observations, limitations, and decision."],[Gauge,"Product definition","Controlled technical characteristics and configuration boundaries."],[Factory,"Production readiness","Tooling, process, quality, packaging, people, and trial-production status."],[RefreshCw,"Change history","Authorized improvements, affected definitions, implementation, and verification."]].map(([Icon,title,copy],index)=>{const OutputIcon=Icon as typeof FileCheck2;return <Reveal key={title as string} delay={(index%3)*.05} className="rounded-2xl border border-ink-950/10 bg-white p-7"><OutputIcon aria-hidden="true" className="text-signal-600" size={27}/><h3 className="mt-9 text-xl font-semibold">{title as string}</h3><p className="mt-4 text-sm leading-6 text-slate-700">{copy as string}</p></Reveal>})}</div></div></section>

      <section className="relative overflow-hidden bg-signal-600 py-24 text-white md:py-32"><div className="container-shell relative grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><Reveal><p className="eyebrow text-white/70">Bring us the unsolved constraint</p><h2 className="mt-6 max-w-5xl text-5xl font-semibold leading-[1.02] tracking-[-.055em] text-balance md:text-7xl">Turn a field problem into a development brief.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/80">Share the environment, current approach, failure mode, target outcome, constraints, volume context, and evidence already available.</p></Reveal><Reveal delay={.1}><Link className="button border-white bg-white text-ink-950 hover:bg-paper-50" href="/request-a-quote">Start a custom project <ArrowRight aria-hidden="true" size={18}/></Link></Reveal></div></section>
    </>
  );
}
